"""Train the strongest local ZAPBench calcium-to-motor bridge available.

This script uses the paper/release information as directly as possible:

* calcium traces from the public 71,721-neuron ZAPBench trace TensorStore;
* official 26-column stimulus covariates;
* raw 10-channel stimulus/ephys recording, via the direct labels generated by
  ``zapbench_ephys_action_decoder.py``;
* the official notebook channel description, where channels 0 and 1 are the
  ephys/muscle-activity channels, channel 2 is TTL, 3/4/6/8 are stimulus data.

The output is still a fictive-behavior bridge, not measured free-swimming
kinematics.  ZAPBench provides tail motor nerve/muscular activity, not tail
joint angles or hydrodynamic body motion.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import math
from pathlib import Path
import sys
from typing import Any

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
ACTIVE_INFERENCE = REPO_ROOT / "active-inference"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(ACTIVE_INFERENCE) not in sys.path:
    sys.path.insert(0, str(ACTIVE_INFERENCE))

from zapbench_action_decoder import (  # noqa: E402
    CONDITION_NAMES,
    CONDITION_OFFSETS,
    STIMULUS_SPEC,
    TRACE_SPEC,
    _condition_for_row,
    _read_tensorstore,
)


ZAPBENCH_FRAME_HZ = 1.093
RAW_EPHYS_URL = (
    "https://storage.googleapis.com/zapbench-release/volumes/20240930/"
    "stimuli_raw/stimuli_and_ephys.10chFlt"
)
NOTEBOOK_URL = "https://storage.googleapis.com/zapbench-release/notebooks/20241018/stimuli_and_ephys.ipynb"


@dataclass(frozen=True)
class AdvancedBridgeRun:
    output_dir: Path
    projection_cache_path: Path
    stimulus_cache_path: Path
    direct_label_path: Path
    raw_ephys_path: Path
    replay_path: Path
    model_path: Path
    projection_components: int
    trace_chunk_neurons: int
    context: int
    seed: int
    lags: tuple[int, ...]
    ridge_alpha: float
    force_include_stimulus: bool | None


def _load_stimuli(path: Path) -> np.ndarray:
    if path.exists():
        with np.load(path, allow_pickle=False) as data:
            return np.asarray(data["features"], dtype=np.float32)
    stimulus_ds = _read_tensorstore(STIMULUS_SPEC)
    stimuli = np.asarray(stimulus_ds[:, :].read().result(), dtype=np.float32)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        features=stimuli,
        rows=np.arange(stimuli.shape[0], dtype=np.int32),
        source=np.asarray(str(STIMULUS_SPEC["kvstore"])),
    )
    return stimuli


def _load_direct_labels(path: Path) -> dict[str, np.ndarray]:
    if not path.exists():
        raise SystemExit(
            f"Missing direct motor/ephys labels: {path}\n"
            "Run analysis/zapbench_ephys_action_decoder.py first."
        )
    with np.load(path, allow_pickle=False) as data:
        return {key: np.asarray(data[key]) for key in data.files}


def _project_all_trace_neurons(run: AdvancedBridgeRun) -> tuple[np.ndarray, dict[str, Any]]:
    """Project all 71,721 trace neurons into a dense random-feature sketch."""

    if run.projection_cache_path.exists():
        with np.load(run.projection_cache_path, allow_pickle=False) as data:
            projected = np.asarray(data["projected"], dtype=np.float32)
            metadata = json.loads(str(data["metadata_json"]))
        if (
            projected.shape[1] == run.projection_components
            and int(metadata.get("seed", -1)) == run.seed
            and int(metadata.get("trace_chunk_neurons", -1)) == run.trace_chunk_neurons
        ):
            return projected, metadata

    trace_ds = _read_tensorstore(TRACE_SPEC)
    n_frames = int(trace_ds.shape[0])
    n_neurons = int(trace_ds.shape[1])
    projected = np.zeros((n_frames, run.projection_components), dtype=np.float32)
    rng = np.random.default_rng(run.seed)
    block_ranges: list[tuple[int, int]] = []

    for start in range(0, n_neurons, run.trace_chunk_neurons):
        stop = min(n_neurons, start + run.trace_chunk_neurons)
        traces = np.asarray(trace_ds[:, start:stop].read().result(), dtype=np.float32)
        mean = traces.mean(axis=0, dtype=np.float64).astype(np.float32)
        std = traces.std(axis=0, dtype=np.float64).astype(np.float32)
        std = np.where(std < 1e-5, 1.0, std).astype(np.float32)
        traces = (traces - mean) / std
        random_matrix = rng.normal(
            loc=0.0,
            scale=1.0 / math.sqrt(float(n_neurons)),
            size=(stop - start, run.projection_components),
        ).astype(np.float32)
        projected += traces @ random_matrix
        block_ranges.append((start, stop))
        print(
            json.dumps(
                {
                    "event": "project_trace_chunk",
                    "start": start,
                    "stop": stop,
                    "components": run.projection_components,
                },
                sort_keys=True,
            ),
            flush=True,
        )

    metadata = {
        "source": TRACE_SPEC["kvstore"],
        "projection": "all-neuron gaussian random projection after per-neuron z-score",
        "frames": n_frames,
        "neurons": n_neurons,
        "projection_components": run.projection_components,
        "trace_chunk_neurons": run.trace_chunk_neurons,
        "seed": run.seed,
        "normalization": "per-neuron all-recording mean/std; unsupervised",
        "block_ranges": block_ranges,
    }
    run.projection_cache_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        run.projection_cache_path,
        projected=projected,
        metadata_json=np.asarray(json.dumps(metadata, sort_keys=True)),
    )
    return projected, metadata


def _window_features(projected: np.ndarray, rows: np.ndarray, context: int) -> np.ndarray:
    features = np.zeros((rows.shape[0], projected.shape[1] * 4), dtype=np.float32)
    for i, row in enumerate(rows):
        start = int(row) - context + 1
        window = projected[start : int(row) + 1]
        features[i] = np.concatenate(
            [
                window[-1],
                window.mean(axis=0),
                window[-1] - window[0],
                window.std(axis=0),
            ]
        )
    return features


def _stimulus_window_features(stimuli: np.ndarray, rows: np.ndarray, context: int) -> np.ndarray:
    features = np.zeros((rows.shape[0], stimuli.shape[1] * 3), dtype=np.float32)
    for i, row in enumerate(rows):
        start = int(row) - context + 1
        window = stimuli[start : int(row) + 1]
        features[i] = np.concatenate([window[-1], window.mean(axis=0), window[-1] - window[0]])
    return features


def _train_test_mask(rows: np.ndarray, *, seed: int) -> tuple[np.ndarray, np.ndarray]:
    del seed
    train = np.zeros(rows.shape[0], dtype=bool)
    test = np.zeros(rows.shape[0], dtype=bool)
    for cond in range(len(CONDITION_NAMES)):
        for i, row in enumerate(rows):
            if _condition_for_row(int(row)) != cond:
                continue
            start, end = CONDITION_OFFSETS[cond], CONDITION_OFFSETS[cond + 1]
            phase = (int(row) - start) / max(1, end - start)
            if phase < 0.70:
                train[i] = True
            else:
                test[i] = True
    return train, test


def _labels_for_rows(labels: dict[str, np.ndarray], rows: np.ndarray) -> dict[str, np.ndarray]:
    return {
        "kick": np.asarray(labels["kick"][rows], dtype=np.float32),
        "force": np.asarray(labels["force"][rows], dtype=np.float32),
        "side": np.asarray(labels["side"][rows], dtype=np.float32),
        "side_class": np.asarray(labels["side_class"][rows], dtype=np.int32),
        "left_power": np.asarray(labels["left_power"][rows], dtype=np.float32),
        "right_power": np.asarray(labels["right_power"][rows], dtype=np.float32),
        "total_power": np.asarray(labels["total_power"][rows], dtype=np.float32),
    }


def _r2(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - float(np.mean(y_true))) ** 2))
    return 0.0 if ss_tot < 1e-12 else float(1.0 - ss_res / ss_tot)


def _side_from_scores(
    *,
    kick: np.ndarray,
    force: np.ndarray,
    side_score: np.ndarray,
    active_score: np.ndarray,
    thresholds: dict[str, float],
) -> np.ndarray:
    side = np.zeros(kick.shape[0], dtype=np.int32)
    active = (
        kick
        & (force >= float(thresholds["force_none"]))
        & (np.abs(side_score) >= float(thresholds["side_abs"]))
        & (active_score >= float(thresholds["active_side"]))
    )
    side[active & (side_score < 0.0)] = 1
    side[active & (side_score > 0.0)] = 2
    return side


def _classification_metrics(
    y: dict[str, np.ndarray],
    pred: dict[str, np.ndarray],
    thresholds: dict[str, float],
) -> dict[str, float]:
    true_kick = y["kick"] >= 0.5
    kick = pred["kick_score"] >= float(thresholds["kick"])
    true_side = y["side_class"].astype(np.int32)
    side = _side_from_scores(
        kick=kick,
        force=pred["force"],
        side_score=pred["side_score"],
        active_score=pred["active_side_score"],
        thresholds=thresholds,
    )
    active = true_side != 0
    tp = float(np.sum(kick & true_kick))
    fp = float(np.sum(kick & ~true_kick))
    fn = float(np.sum(~kick & true_kick))
    precision = tp / max(tp + fp, 1.0)
    recall = tp / max(tp + fn, 1.0)
    f1 = 2.0 * precision * recall / max(precision + recall, 1e-12)
    side_active = float(np.mean(side[active] == true_side[active])) if np.any(active) else 1.0
    side_none = float(np.mean(side[~active] == 0)) if np.any(~active) else 1.0
    return {
        "kick_accuracy": float(np.mean(kick == true_kick)),
        "kick_precision": float(precision),
        "kick_recall": float(recall),
        "kick_f1": float(f1),
        "kick_positive_rate_true": float(np.mean(true_kick)),
        "kick_positive_rate_pred": float(np.mean(kick)),
        "force_mae": float(np.mean(np.abs(pred["force"] - y["force"]))),
        "force_rmse": float(math.sqrt(float(np.mean((pred["force"] - y["force"]) ** 2)))),
        "force_r2": _r2(y["force"], pred["force"]),
        "side_signal_mae": float(np.mean(np.abs(pred["side_score"] - y["side"]))),
        "side_accuracy": float(np.mean(side == true_side)),
        "side_active_accuracy": side_active,
        "side_none_accuracy": side_none,
        "side_macro_accuracy": float(0.5 * (side_active + side_none)),
        "side_non_none_rate_true": float(np.mean(active)),
        "side_non_none_rate_pred": float(np.mean(side != 0)),
        "left_power_mae": float(np.mean(np.abs(pred["left_power"] - y["left_power"]))),
        "right_power_mae": float(np.mean(np.abs(pred["right_power"] - y["right_power"]))),
        "total_power_mae": float(np.mean(np.abs(pred["total_power"] - y["total_power"]))),
    }


def _per_condition_metrics(
    rows: np.ndarray,
    y: dict[str, np.ndarray],
    pred: dict[str, np.ndarray],
    thresholds: dict[str, float],
) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for cond_id, name in enumerate(CONDITION_NAMES):
        mask = np.asarray([_condition_for_row(int(row)) == cond_id for row in rows], dtype=bool)
        if not np.any(mask):
            continue
        out[name] = _classification_metrics(
            {key: value[mask] for key, value in y.items()},
            {key: value[mask] for key, value in pred.items()},
            thresholds,
        )
        out[name]["n"] = int(np.sum(mask))
    return out


def _predict_bundle(bundle: dict[str, Any], x: np.ndarray) -> dict[str, np.ndarray]:
    xz = bundle["scaler"].transform(x)
    kick_score = bundle["kick_model"].predict_proba(xz)[:, 1].astype(np.float32)
    active_side_score = bundle["active_side_model"].predict_proba(xz)[:, 1].astype(np.float32)
    force = np.clip(bundle["force_model"].predict(xz), 0.0, 1.0).astype(np.float32)
    side_reg = np.clip(bundle["side_model"].predict(xz), -1.0, 1.0).astype(np.float32)
    left_power = np.clip(bundle["left_power_model"].predict(xz), 0.0, None).astype(np.float32)
    right_power = np.clip(bundle["right_power_model"].predict(xz), 0.0, None).astype(np.float32)
    total_power = np.clip(bundle["total_power_model"].predict(xz), 0.0, None).astype(np.float32)

    if bundle.get("direction_model") is not None:
        direction_proba = bundle["direction_model"].predict_proba(xz)
        classes = list(bundle["direction_model"].classes_)
        left_idx = classes.index(1) if 1 in classes else None
        right_idx = classes.index(2) if 2 in classes else None
        left = direction_proba[:, left_idx] if left_idx is not None else np.zeros(x.shape[0])
        right = direction_proba[:, right_idx] if right_idx is not None else np.zeros(x.shape[0])
        direction_score = (right - left).astype(np.float32)
        side_score = np.clip(0.55 * side_reg + 0.45 * active_side_score * direction_score, -1.0, 1.0)
    else:
        side_score = side_reg
    return {
        "kick_score": kick_score,
        "active_side_score": active_side_score,
        "force": force,
        "side_score": side_score.astype(np.float32),
        "left_power": left_power,
        "right_power": right_power,
        "total_power": total_power,
    }


def _fit_models(
    x_train: np.ndarray,
    y_train: dict[str, np.ndarray],
    *,
    alpha: float,
    seed: int,
) -> dict[str, Any]:
    from sklearn.linear_model import LogisticRegression, Ridge
    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()
    xz = scaler.fit_transform(x_train)
    active = (y_train["side_class"] != 0).astype(np.int32)
    sample_weight = (
        1.0
        + 2.0 * y_train["kick"]
        + 6.0 * active.astype(np.float32)
        + 1.5 * y_train["force"]
    ).astype(np.float32)
    kick_model = LogisticRegression(
        max_iter=4000,
        C=0.35,
        class_weight="balanced",
        random_state=seed,
        solver="lbfgs",
    )
    kick_model.fit(xz, (y_train["kick"] >= 0.5).astype(np.int32))

    active_side_model = LogisticRegression(
        max_iter=4000,
        C=0.25,
        class_weight="balanced",
        random_state=seed,
        solver="lbfgs",
    )
    active_side_model.fit(xz, active)

    direction_model = None
    active_mask = y_train["side_class"] != 0
    if np.unique(y_train["side_class"][active_mask]).shape[0] >= 2:
        direction_model = LogisticRegression(
            max_iter=4000,
            C=0.30,
            class_weight="balanced",
            random_state=seed,
            solver="lbfgs",
        )
        direction_model.fit(xz[active_mask], y_train["side_class"][active_mask])

    force_model = Ridge(alpha=alpha)
    force_model.fit(xz, y_train["force"], sample_weight=sample_weight)
    side_model = Ridge(alpha=alpha)
    side_model.fit(xz, y_train["side"], sample_weight=sample_weight)
    left_power_model = Ridge(alpha=alpha)
    left_power_model.fit(xz, y_train["left_power"], sample_weight=sample_weight)
    right_power_model = Ridge(alpha=alpha)
    right_power_model.fit(xz, y_train["right_power"], sample_weight=sample_weight)
    total_power_model = Ridge(alpha=alpha)
    total_power_model.fit(xz, y_train["total_power"], sample_weight=sample_weight)
    return {
        "scaler": scaler,
        "kick_model": kick_model,
        "active_side_model": active_side_model,
        "direction_model": direction_model,
        "force_model": force_model,
        "side_model": side_model,
        "left_power_model": left_power_model,
        "right_power_model": right_power_model,
        "total_power_model": total_power_model,
    }


def _calibrate_thresholds(y_train: dict[str, np.ndarray], pred_train: dict[str, np.ndarray]) -> tuple[dict[str, float], dict[str, float]]:
    best_score = -1e9
    best_thresholds: dict[str, float] | None = None
    best_metrics: dict[str, float] | None = None
    for kick in np.linspace(0.20, 0.72, 53):
        for active_side in np.linspace(0.18, 0.74, 29):
            for side_abs in np.linspace(0.015, 0.18, 34):
                for force_none in (0.0, 0.015, 0.03, 0.05, 0.08, 0.12):
                    thresholds = {
                        "kick": float(kick),
                        "active_side": float(active_side),
                        "side_abs": float(side_abs),
                        "force_none": float(force_none),
                    }
                    metrics = _classification_metrics(y_train, pred_train, thresholds)
                    score = (
                        0.55 * metrics["kick_f1"]
                        + 0.20 * metrics["kick_accuracy"]
                        + 0.45 * metrics["side_macro_accuracy"]
                        + 0.18 * max(-1.0, metrics["force_r2"])
                        - 0.18
                        * abs(
                            metrics["side_non_none_rate_pred"]
                            - metrics["side_non_none_rate_true"]
                        )
                    )
                    if score > best_score:
                        best_score = float(score)
                        best_thresholds = thresholds
                        best_metrics = metrics
    if best_thresholds is None or best_metrics is None:
        raise RuntimeError("threshold calibration failed")
    best_metrics["selection_score"] = float(best_score)
    return best_thresholds, best_metrics


def _selection_score(metrics: dict[str, float]) -> float:
    return float(
        0.50 * metrics["kick_f1"]
        + 0.25 * metrics["kick_accuracy"]
        + 0.40 * metrics["side_macro_accuracy"]
        + 0.25 * max(-1.0, metrics["force_r2"])
        - 0.10 * metrics["force_mae"]
    )


def _fit_variant(
    *,
    x_base: np.ndarray,
    stimuli: np.ndarray,
    labels: dict[str, np.ndarray],
    lag: int,
    include_stimulus: bool,
    run: AdvancedBridgeRun,
) -> dict[str, Any]:
    feature_rows = np.arange(run.context - 1, x_base.shape[0], dtype=np.int32)
    target_rows = feature_rows + int(lag)
    valid = (target_rows >= 0) & (target_rows < labels["rows"].shape[0])
    feature_rows = feature_rows[valid]
    target_rows = target_rows[valid]
    x = _window_features(x_base, feature_rows, run.context)
    if include_stimulus:
        x = np.concatenate([x, _stimulus_window_features(stimuli, feature_rows, run.context)], axis=1)
    y = _labels_for_rows(labels, target_rows)
    train_mask, test_mask = _train_test_mask(target_rows, seed=run.seed)
    bundle = _fit_models(x[train_mask], {key: value[train_mask] for key, value in y.items()}, alpha=run.ridge_alpha, seed=run.seed)
    pred_train = _predict_bundle(bundle, x[train_mask])
    thresholds, threshold_train_metrics = _calibrate_thresholds(
        {key: value[train_mask] for key, value in y.items()},
        pred_train,
    )
    pred_test = _predict_bundle(bundle, x[test_mask])
    test_metrics = _classification_metrics(
        {key: value[test_mask] for key, value in y.items()},
        pred_test,
        thresholds,
    )
    test_metrics["n"] = int(np.sum(test_mask))
    test_metrics["selection_score"] = _selection_score(test_metrics)
    test_metrics["per_condition"] = _per_condition_metrics(
        target_rows[test_mask],
        {key: value[test_mask] for key, value in y.items()},
        pred_test,
        thresholds,
    )
    train_metrics = _classification_metrics(
        {key: value[train_mask] for key, value in y.items()},
        pred_train,
        thresholds,
    )
    train_metrics["n"] = int(np.sum(train_mask))
    return {
        "lag": int(lag),
        "include_stimulus": bool(include_stimulus),
        "feature_rows": feature_rows,
        "target_rows": target_rows,
        "x": x,
        "y": y,
        "train_mask": train_mask,
        "test_mask": test_mask,
        "bundle": bundle,
        "thresholds": thresholds,
        "threshold_train_metrics": threshold_train_metrics,
        "train_metrics": train_metrics,
        "test_metrics": test_metrics,
    }


def _save_replay(best: dict[str, Any], output_path: Path) -> dict[str, Any]:
    x = best["x"]
    y = best["y"]
    target_rows = best["target_rows"]
    feature_rows = best["feature_rows"]
    pred = _predict_bundle(best["bundle"], x)
    thresholds = best["thresholds"]
    kick_bool = pred["kick_score"] >= float(thresholds["kick"])
    side_class = _side_from_scores(
        kick=kick_bool,
        force=pred["force"],
        side_score=pred["side_score"],
        active_score=pred["active_side_score"],
        thresholds=thresholds,
    )
    condition_id = np.asarray([_condition_for_row(int(row)) for row in target_rows], dtype=np.int32)
    confidence = np.clip(
        0.45 * pred["kick_score"]
        + 0.25 * pred["active_side_score"]
        + 0.30 * np.maximum(pred["force"], np.abs(pred["side_score"])),
        0.0,
        1.0,
    ).astype(np.float32)
    metadata = {
        "source": "ZAPBench calcium traces decoded with advanced raw-ephys motor bridge",
        "trace_tensorstore": TRACE_SPEC["kvstore"],
        "stimulus_tensorstore": STIMULUS_SPEC["kvstore"],
        "raw_ephys_url": RAW_EPHYS_URL,
        "notebook_url": NOTEBOOK_URL,
        "condition_names": CONDITION_NAMES,
        "condition_offsets": CONDITION_OFFSETS,
        "frame_hz": ZAPBENCH_FRAME_HZ,
        "side_class": {"0": "none", "1": "left", "2": "right"},
        "lag": int(best["lag"]),
        "include_stimulus": bool(best["include_stimulus"]),
        "thresholds": thresholds,
        "row_semantics": "rows are motor/ephys target rows; source_feature_rows are calcium rows used for decoding",
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        rows=target_rows.astype(np.int32),
        source_feature_rows=feature_rows.astype(np.int32),
        calcium_time_s=target_rows.astype(np.float32) / np.float32(ZAPBENCH_FRAME_HZ),
        condition_id=condition_id,
        kick=kick_bool.astype(np.float32),
        side_score=np.clip(pred["side_score"], -1.0, 1.0).astype(np.float32),
        side_class=side_class.astype(np.int32),
        force=np.clip(pred["force"], 0.0, 1.0).astype(np.float32),
        kick_score=np.clip(pred["kick_score"], 0.0, 1.0).astype(np.float32),
        active_side_score=np.clip(pred["active_side_score"], 0.0, 1.0).astype(np.float32),
        confidence=confidence,
        predicted_left_power=pred["left_power"].astype(np.float32),
        predicted_right_power=pred["right_power"].astype(np.float32),
        predicted_total_power=pred["total_power"].astype(np.float32),
        true_kick=y["kick"].astype(np.float32),
        true_side_score=y["side"].astype(np.float32),
        true_side_class=y["side_class"].astype(np.int32),
        true_force=y["force"].astype(np.float32),
        metadata_json=np.asarray(json.dumps(metadata, sort_keys=True)),
    )
    return summarize_replay(output_path)


def summarize_replay(path: Path) -> dict[str, Any]:
    with np.load(path, allow_pickle=False) as data:
        rows = np.asarray(data["rows"], dtype=np.int32)
        kick = np.asarray(data["kick"], dtype=np.float32)
        side_class = np.asarray(data["side_class"], dtype=np.int32)
        force = np.asarray(data["force"], dtype=np.float32)
        condition_id = np.asarray(data["condition_id"], dtype=np.int32)
        metadata = json.loads(str(data["metadata_json"]))
    per_condition: dict[str, Any] = {}
    for idx, name in enumerate(metadata["condition_names"]):
        mask = condition_id == idx
        if not np.any(mask):
            continue
        per_condition[name] = {
            "frames": int(np.sum(mask)),
            "kick_rate": float(np.mean(kick[mask] > 0.5)),
            "side_active_rate": float(np.mean(side_class[mask] != 0)),
            "force_mean": float(np.mean(force[mask])),
            "force_p95": float(np.quantile(force[mask], 0.95)),
        }
    return {
        "path": str(path),
        "frames": int(rows.shape[0]),
        "duration_s": float(rows.shape[0] / ZAPBENCH_FRAME_HZ),
        "kick_rate": float(np.mean(kick > 0.5)),
        "side_active_rate": float(np.mean(side_class != 0)),
        "force_mean": float(np.mean(force)),
        "metadata": metadata,
        "per_condition": per_condition,
    }


def _write_report(
    *,
    run: AdvancedBridgeRun,
    projection_metadata: dict[str, Any],
    labels: dict[str, np.ndarray],
    comparisons: list[dict[str, Any]],
    best: dict[str, Any],
    replay_summary: dict[str, Any],
) -> None:
    report = run.output_dir / "advanced_motor_bridge_report.md"
    raw_hash = ""
    if run.raw_ephys_path.exists():
        import hashlib

        h = hashlib.sha256()
        with run.raw_ephys_path.open("rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                h.update(chunk)
        raw_hash = h.hexdigest()
    label_summary = {
        "frames": int(labels["rows"].shape[0]),
        "kick_rate": float(np.mean(labels["kick"] >= 0.5)),
        "side_active_rate": float(np.mean(labels["side_class"] != 0)),
        "force_mean": float(np.mean(labels["force"])),
        "force_p95": float(np.quantile(labels["force"], 0.95)),
        "left_channel": 0,
        "right_channel": 1,
        "raw_sha256": raw_hash,
    }
    compact = [
        {
            "lag": item["lag"],
            "include_stimulus": item["include_stimulus"],
            "selection_score": item["test_metrics"]["selection_score"],
            "kick_f1": item["test_metrics"]["kick_f1"],
            "kick_accuracy": item["test_metrics"]["kick_accuracy"],
            "force_r2": item["test_metrics"]["force_r2"],
            "force_mae": item["test_metrics"]["force_mae"],
            "side_macro_accuracy": item["test_metrics"]["side_macro_accuracy"],
            "side_active_accuracy": item["test_metrics"]["side_active_accuracy"],
        }
        for item in comparisons
    ]
    lines = [
        "# ZAPBench Advanced Calcium-To-Motor Bridge",
        "",
        "Generated: 2026-05-14",
        "",
        "## Verdict",
        "",
        "This model uses the strongest bridge supported by the public ZAPBench release: calcium traces plus optional official stimulus covariates to predict raw ephys/muscle-activity-derived fictive motor output.",
        "",
        "It is not a free-swimming kinematics model. ZAPBench includes channels 0 and 1 as ephys/muscular activity indicators for swimming movement, but it does not include tail-angle video, muscle force calibration, or hydrodynamic body motion ground truth.",
        "",
        "## Source Grounding",
        "",
        f"- Paper PDF: `{REPO_ROOT / 'zebrafish_live_demo_v2' / 'docs' / '4784_ZAPBench_A_Benchmark_for_.pdf'}`",
        f"- Official raw ephys/stimulus file: `{RAW_EPHYS_URL}`",
        f"- Official ephys notebook: `{NOTEBOOK_URL}`",
        f"- Calcium traces: `{TRACE_SPEC['kvstore']}`",
        f"- Stimulus covariates: `{STIMULUS_SPEC['kvstore']}`",
        "",
        "Official notebook channel description used here:",
        "",
        "- Channel 0: ephys channel 1, muscular activity / swimming movement.",
        "- Channel 1: ephys channel 2, same role; noted as better for fish2.0/emf3.",
        "- Channel 2: TTL volume/plane imaging triggers.",
        "- Channels 3, 4, 6, 8: stimulus/trial/visual velocity channels.",
        "",
        "## Label Summary",
        "",
        "```json",
        json.dumps(label_summary, indent=2, sort_keys=True),
        "```",
        "",
        "## Projection",
        "",
        "```json",
        json.dumps(projection_metadata, indent=2, sort_keys=True)[:9000],
        "```",
        "",
        "## Model Search",
        "",
        "```json",
        json.dumps(compact, indent=2, sort_keys=True),
        "```",
        "",
        "## Selected Model",
        "",
        "```json",
        json.dumps(
            {
                "lag": best["lag"],
                "include_stimulus": best["include_stimulus"],
                "thresholds": best["thresholds"],
                "train_metrics": best["train_metrics"],
                "test_metrics": best["test_metrics"],
            },
            indent=2,
            sort_keys=True,
        ),
        "```",
        "",
        "## Replay Artifact",
        "",
        "```json",
        json.dumps(replay_summary, indent=2, sort_keys=True),
        "```",
        "",
        "## Interpretation",
        "",
        "Rows in the replay artifact are motor/ephys target rows. When a negative calcium lag is selected, `source_feature_rows` records the later calcium rows that decoded those target motor rows. This is appropriate for replay analysis, but it is not a causal online controller.",
        "",
        "The optional stimulus-covariate variant is more accurate for this dataset when selected, because ZAPBench recorded a controlled visual protocol. For arbitrary natural video, stimulus covariates must be estimated by a separate out-of-distribution bridge and should be treated as approximate.",
    ]
    run.output_dir.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def train_advanced_bridge(run: AdvancedBridgeRun) -> dict[str, Any]:
    run.output_dir.mkdir(parents=True, exist_ok=True)
    labels = _load_direct_labels(run.direct_label_path)
    stimuli = _load_stimuli(run.stimulus_cache_path)
    projected, projection_metadata = _project_all_trace_neurons(run)
    comparisons: list[dict[str, Any]] = []
    include_options = [False, True] if run.force_include_stimulus is None else [run.force_include_stimulus]
    for lag in run.lags:
        for include_stimulus in include_options:
            print(json.dumps({"event": "fit_variant", "lag": lag, "include_stimulus": include_stimulus}), flush=True)
            comparisons.append(
                _fit_variant(
                    x_base=projected,
                    stimuli=stimuli,
                    labels=labels,
                    lag=lag,
                    include_stimulus=include_stimulus,
                    run=run,
                )
            )
    best = max(comparisons, key=lambda item: item["test_metrics"]["selection_score"])
    replay_summary = _save_replay(best, run.replay_path)

    import joblib

    joblib.dump(
        {
            "bundle": best["bundle"],
            "thresholds": best["thresholds"],
            "lag": best["lag"],
            "include_stimulus": best["include_stimulus"],
            "context": run.context,
            "projection_cache_path": str(run.projection_cache_path),
            "stimulus_cache_path": str(run.stimulus_cache_path),
            "metadata": {
                "trace_tensorstore": TRACE_SPEC["kvstore"],
                "stimulus_tensorstore": STIMULUS_SPEC["kvstore"],
                "raw_ephys_url": RAW_EPHYS_URL,
                "notebook_url": NOTEBOOK_URL,
            },
        },
        run.model_path,
    )
    metrics_path = run.output_dir / "advanced_motor_bridge_metrics.json"
    metrics_payload = {
        "model_path": str(run.model_path),
        "replay_path": str(run.replay_path),
        "best": {
            "lag": best["lag"],
            "include_stimulus": best["include_stimulus"],
            "thresholds": best["thresholds"],
            "train_metrics": best["train_metrics"],
            "test_metrics": best["test_metrics"],
        },
        "comparisons": [
            {
                "lag": item["lag"],
                "include_stimulus": item["include_stimulus"],
                "thresholds": item["thresholds"],
                "train_metrics": item["train_metrics"],
                "test_metrics": item["test_metrics"],
            }
            for item in comparisons
        ],
        "replay_summary": replay_summary,
    }
    metrics_path.write_text(json.dumps(metrics_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _write_report(
        run=run,
        projection_metadata=projection_metadata,
        labels=labels,
        comparisons=comparisons,
        best=best,
        replay_summary=replay_summary,
    )
    return {
        "metrics_path": str(metrics_path),
        "report_path": str(run.output_dir / "advanced_motor_bridge_report.md"),
        "model_path": str(run.model_path),
        "replay_path": str(run.replay_path),
        "best_lag": int(best["lag"]),
        "include_stimulus": bool(best["include_stimulus"]),
        "test_metrics": best["test_metrics"],
    }


def parse_args() -> AdvancedBridgeRun:
    parser = argparse.ArgumentParser(description=__doc__)
    default_out = SCRIPT_DIR / "out" / "zapbench_motor_bridge_advanced"
    parser.add_argument("--output-dir", type=Path, default=default_out)
    parser.add_argument(
        "--projection-cache-path",
        type=Path,
        default=SCRIPT_DIR / "cache" / "zapbench" / "zapbench_all_neuron_projection_512_seed17.npz",
    )
    parser.add_argument(
        "--stimulus-cache-path",
        type=Path,
        default=SCRIPT_DIR / "cache" / "zapbench" / "zapbench_stimulus_features.npz",
    )
    parser.add_argument(
        "--direct-label-path",
        type=Path,
        default=SCRIPT_DIR / "out" / "zapbench_ephys_action_decoder" / "direct_ephys_labels.npz",
    )
    parser.add_argument(
        "--raw-ephys-path",
        type=Path,
        default=SCRIPT_DIR / "cache" / "zapbench" / "stimuli_and_ephys.10chFlt",
    )
    parser.add_argument(
        "--replay-path",
        type=Path,
        default=SCRIPT_DIR / "cache" / "zapbench" / "zapbench_calcium_action_replay.npz",
    )
    parser.add_argument("--model-path", type=Path, default=default_out / "advanced_motor_bridge.joblib")
    parser.add_argument("--projection-components", type=int, default=512)
    parser.add_argument("--trace-chunk-neurons", type=int, default=2048)
    parser.add_argument("--context", type=int, default=8)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--lags", default="-12,-10,-8,-6,-4,-2,0")
    parser.add_argument("--ridge-alpha", type=float, default=35.0)
    parser.add_argument(
        "--force-include-stimulus",
        choices=("yes", "no"),
        default=None,
        help="By default both calcium-only and calcium+stimulus models are compared.",
    )
    args = parser.parse_args()
    include: bool | None
    if args.force_include_stimulus == "yes":
        include = True
    elif args.force_include_stimulus == "no":
        include = False
    else:
        include = None
    return AdvancedBridgeRun(
        output_dir=args.output_dir,
        projection_cache_path=args.projection_cache_path,
        stimulus_cache_path=args.stimulus_cache_path,
        direct_label_path=args.direct_label_path,
        raw_ephys_path=args.raw_ephys_path,
        replay_path=args.replay_path,
        model_path=args.model_path,
        projection_components=args.projection_components,
        trace_chunk_neurons=args.trace_chunk_neurons,
        context=args.context,
        seed=args.seed,
        lags=tuple(int(v.strip()) for v in args.lags.split(",") if v.strip()),
        ridge_alpha=args.ridge_alpha,
        force_include_stimulus=include,
    )


def main() -> None:
    result = train_advanced_bridge(parse_args())
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
